name: weatherhub
description: "A Weather app by Sonnami Develops"
publish_to: 'none'

version: 1.2.0+4

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  lottie: ^3.6.1
  geolocator: ^14.0.3
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0
  shared_preferences: ^2.2.0
  github_release_apk_updater: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  remove_alpha_ios: true
